### ISSUE TITLE
Inverse Dynamics

### ISSUE THREAD

**Issue by ksachikonye** [BMClab/bmc#36]
I have looked through your notes and they are brilliant. I have skimmed through your notes and have a shallow grasp of some of the concepts. Lets say someone has smart shoes and other wearables that can record the ground contact time, strike angle, left/right foot balance, distance, heart rate, muscle impulses, flight time, stride length, pace, cadence and so on, but not the force applied to the ground nor the ground reaction forces. Can I use inverse dynamics to determine the forces given all the other parameters? If I apply body segmentation and calculate my centre of mass and centre of pressure, can that be converted into a time series ? Does the position of the centre of mass affect posture and form ? When accounting for drag, how big is the difference in the surfaces of a cyclist and a sprinter ? Another question I have would be, if say, someone was on a wind surfing board and could accurately locate their position on a body of water using gps and also using an accelerometer on the sail, how would one apply inverse dynamics to calculate bouyancy forces, forces on an individual, and the propulsion force ?

**Comment by demotu** [comment]
yes, in theory you can use wearable sensors to get the data and apply inverse dynamics. Google for inverse dynamics using wearable sensors you'll find some work on this. It should be possible to use wearable sensors to apply to windsurfing as well, but I bet there will be a lot of technical challenges to do that.
