### ISSUE TITLE
Thx for the greate tutorials! 

### ISSUE THREAD

**Issue by extraymond** [BMClab/BMC#4]
First of all, thank you for writing such a great tutorial. It's both informative and detailed.
I'm very interested in using python to do biomechanics simulation and control.

Is there any plan for adding more tutorials on motor control? I've found it scarce not only in python control but also in biomechanics. I'm mostly interested in using control theory for biomechanics control.

Thx for all you've done!

**Comment by demotu** [comment]
About classical control theory applied to human movement, see for example:  
- Ton Van Den Bogert Tutorial: [https://youtu.be/Z4BoVVpju88](https://youtu.be/Z4BoVVpju88)  
- Simulating Robot, Vehicle, Spacecraft, and Animal Motion w/ Python: [https://youtu.be/r4piIKV4sDw](https://youtu.be/r4piIKV4sDw)
